export const FETCH_GAMES = 'FETCH_GAMES';
export const FETCHING_BEST_GAMES = 'FETCHING_BEST_GAMES';
export const FETCHING_BEST_GAMES_SUCCESS = 'FETCHING_BEST_GAMES_SUCCESS';
export const FETCHING_BEST_GAMES_FAIL = 'FETCHING_BEST_GAMES_FAIL';